import { OverviewBrief, OverviewAllocation, OverviewPnl, OverviewFunds } from './OverviewPanels';
import { HoldingLogo } from './HoldingLogo';
import { useAdaptiveRows } from './useAdaptiveRows';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Home, ChartNoAxesCombined, BriefcaseBusiness, Menu, Wallet, TrendingUp, ArrowDownLeft, ArrowUpRight, Bell, ChevronRight, Download, Link2, RefreshCw, Settings2, ShieldCheck, Sparkles, X } from 'lucide-react';
import type { AnalysisReport, AdjustmentPlan, Alert, Holding, MarketQuote, Preferences, WorkbenchState } from '../../lib/ibkr/workbenchTypes';
import { reportMarkdown } from '../../lib/ibkr/workbenchReport';
import { exportAccountCommandDeckPdf } from '../../lib/ibkr/exportAccountPdf';
import { exportSparkFlowResearchPdf } from '../../lib/exportResearchPdf';
import { PerformancePanel, PlanPanel, ResearchDetails } from './WorkbenchPanels';
import { AnalysisWorkspace } from './AnalysisWorkspace';
import { quantity as formatQuantity } from '../../lib/ibkr/workbenchFormat';
import './AccountWorkbench.css';

const api = '/api/ibkr-workbench/';
async function request<T>(endpoint: string, value?: unknown, signal?: AbortSignal): Promise<T> {
  const response = await fetch(api + endpoint, { ...(value === undefined ? {} : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value) }), signal });
  const data = await response.json(); if (!response.ok) throw new Error(data.error || '账户服务暂不可用'); return data;
}
const number = (value: unknown) => value === null || value === undefined || value === '' || !Number.isFinite(Number(value)) ? null : Number(value);
const money = (value: unknown) => { const n = number(value); return n === null ? '—' : n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); };
const pct = (value: number | null | undefined) => value == null ? '—' : `${(value * 100).toFixed(1)}%`;
const time = (value: string | null | undefined) => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '尚未同步';
const actionLabels = { hold: '维持', watch: '观察', increase: '增持', reduce: '减持' };
const quoteLabels = { delayed: '延迟 / 休市参考', stale: '缓存已过期', missing: '行情缺失', unmapped: '待匹配', unsupported: '未覆盖品种' };
type HoldingSortKey = 'quantity' | 'marketValue' | 'weight' | 'unrealizedPnl';
type HoldingSort = { key: HoldingSortKey; direction: 'ascending' | 'descending' };
const holdingSortLabels: Record<HoldingSortKey, string> = { quantity: '数量', marketValue: '市值', weight: '占比', unrealizedPnl: '券商盈亏' };

export function AccountWorkbench() {
  const [state, setState] = useState<WorkbenchState | null>(null);
  const [tab, setTab] = useState<'overview' | 'reports' | 'alerts' | 'holdings' | 'settings'>('overview');
  const [selected, setSelected] = useState<number | null>(null);
  const [report, setReport] = useState<AnalysisReport | null>(null);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const [exporting, setExporting] = useState(false); const [question, setQuestion] = useState(''); const [search, setSearch] = useState('');
  const [holdingSort, setHoldingSort] = useState<HoldingSort | null>(null);
  const [menu,setMenu]=useState(false); const [filter,setFilter]=useState('all'); const [chosenAlert,setChosenAlert]=useState<Alert>(); const [chosenPlan,setChosenPlan]=useState<AdjustmentPlan>(); const [reportId,setReportId]=useState<string>();const [planReportId,setPlanReportId]=useState<string>();const [selectedJobId,setSelectedJobId]=useState<string>();
  const revision = useRef(0);
  const refresh = useCallback(async () => { const current = ++revision.current; const value = await request<WorkbenchState>('state'); if (current === revision.current) setState(value); }, []);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>; let disposed = false;
    const poll = async () => { try { const current = ++revision.current; const value = await request<WorkbenchState>('state', undefined, controller.signal); if (!disposed && current === revision.current) setState(value); if (!document.hidden && value.snapshot.snapshotId) { const quotes = await request<MarketQuote[]>('quotes', undefined, controller.signal); if (!disposed && current === revision.current) setState(previous => previous?.snapshot.accountKey === value.snapshot.accountKey ? { ...previous, quotes } : previous); } } catch (e) { if (!disposed) setError(e instanceof Error ? e.message : '无法连接账户服务'); } finally { if (!disposed) timer = setTimeout(poll, document.hidden ? 15000 : 5000); } };
    void poll(); return () => { disposed = true; ++revision.current; controller.abort(); clearTimeout(timer); };
  }, []);
  const act = async (name: string, endpoint: string, payload: unknown = {}) => {
    if (busy) return; setBusy(name); setError('');
    try { await request(endpoint, payload); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : '操作失败'); } finally { setBusy(''); }
  };
  const connect = async () => {
    // Open synchronously from the user gesture; never navigate an unvalidated authorization URL.
    const popup = window.open('about:blank', '_blank'); if (popup) { popup.opener = null; popup.document.title = '正在连接 IBKR'; popup.document.body.textContent = '正在获取 IBKR 官方授权地址…'; }
    setBusy('connect'); setError('');
    try { const result = await request<{ authorizationUrl?: string; detail: string; state: string }>('connect', {});
      if (!result.authorizationUrl) { popup?.close(); if (result.state === 'connected') { await request('sync', {}); await refresh(); return; } throw new Error(result.detail || '无法获取授权地址'); }
      const url = new URL(result.authorizationUrl); if (url.protocol !== 'https:' || url.hostname !== 'api.ibkr.com') { popup?.close(); throw new Error('官方授权地址校验失败'); }
      if (popup) popup.location.href = url.href; else window.location.assign(url.href);
      await refresh();
    } catch (e) { popup?.close(); setError(e instanceof Error ? e.message : '连接失败'); } finally { setBusy(''); }
  };
  const snapshot=state?.snapshot; const latest=state?.reports.find(r=>r.kind!=='chat'); const holding=snapshot?.positions.find(p=>p.conId===selected);
  const exportAccountPdf = async () => {
    if (!state || exporting) return;
    setExporting(true); setError('');
    try { await exportAccountCommandDeckPdf({ snapshot: state.snapshot, metrics: state.metrics, report: latest }); }
    catch (e) { setError(e instanceof Error ? e.message : 'PDF 导出失败，请重试。'); }
    finally { setExporting(false); }
  };
  useEffect(()=>{setSelected(null);setReport(null);setReportId(undefined);setSelectedJobId(undefined);setChosenPlan(undefined);setChosenAlert(undefined);},[snapshot?.accountKey]);
  useEffect(()=>{if(selected===null&&!report)return;const old=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=document.querySelector<HTMLElement>('.awb-overlay [role="dialog"]');const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,summary')??[]);focusable()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);setReport(null);}if(e.key==='Tab'){const els=focusable();if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els[els.length-1]?.focus();}else if(!e.shiftKey&&document.activeElement===els[els.length-1]){e.preventDefault();els[0]?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);old?.focus();};},[selected,report]);
  const ready=Boolean(snapshot?.snapshotId&&['ready','empty'].includes(snapshot.state));const running=state?.jobs.find(j=>j.state==='running');const task=running??state?.jobs.find(j=>j.id===selectedJobId)??state?.jobs.find(j=>j.state!=='completed'&&(j.progress?.covered.length??0)>0)??state?.jobs[0];const canAnalyze=Boolean(ready&&state?.ai.enabled&&!busy&&!running&&state?.dailyBrief?.state!=='running'&&state.ai.usedToday<state.preferences.maxAiCalls);const alerts=state?.alerts.filter(a=>!a.resolved)??[];const nav=number(snapshot?.metrics.netLiquidation),currency=snapshot?.baseCurrency??'';const cash=snapshot?.cash.find(c=>c.currency===currency)?.amount;
  const filtered=snapshot?.positions.filter(p=>`${p.symbol} ${p.name??''}`.toLowerCase().includes(search.toLowerCase()))??[];const activeReport=state?.reports.find(r=>r.id===reportId)??latest; const pendingReport=state?.jobs.find(j=>j.kind!=='chat'&&j.state!=='completed'&&Date.parse(j.startedAt)>Date.parse(latest?.generatedAt??'1970-01-01'));
  const sortHoldings = (holdings: Holding[]) => !holdingSort ? holdings : holdings.map((holding, index) => ({ holding, index })).sort((a, b) => {
    const value = (holding: Holding) => holdingSort.key === 'weight' ? (nav && nav > 0 && holding.currency === currency ? number(holding.marketValue) === null ? null : Number(holding.marketValue) / nav : null) : number(holding[holdingSort.key]);
    const left = value(a.holding), right = value(b.holding);
    if (left === null) return right === null ? a.index - b.index : 1;
    if (right === null) return -1;
    return (left - right) * (holdingSort.direction === 'ascending' ? 1 : -1) || a.index - b.index;
  }).map(({ holding }) => holding);
  const toggleHoldingSort = (key: HoldingSortKey) => setHoldingSort(current => current?.key === key ? { key, direction: current.direction === 'ascending' ? 'descending' : 'ascending' } : { key, direction: 'ascending' });
  const overviewRows=useAdaptiveRows(snapshot?.positions.length??0,5,'tbody tr',tab==='overview');
  const navigate=(key:typeof tab)=>{setTab(key);setMenu(false);};
  const navItems=[['overview','账户总览',Home],['reports','AI 分析',ChartNoAxesCombined],['alerts','机会与风险',ShieldCheck],['holdings','持仓',BriefcaseBusiness],['settings','设置',Settings2]] as const;
  const titles={overview:'账户总览',reports:'投资组合分析报告',alerts:'机会与风险中心',holdings:'我的持仓',settings:'连接账户与分析偏好'};
  const subtitles={overview:'你的资产、市场与下一步',reports:'完整账户数据一次提交、一次分析、一个结论',alerts:'把市场变化转化为可执行的计划',holdings:'持仓结构与组合风险敞口',settings:'管理账户连接、研究授权与投资约束'};
  const holdingsTable=(compact:boolean)=>{const sortableHeader=(key:HoldingSortKey,label:React.ReactNode)=><th aria-sort={!holdingSort||holdingSort.key!==key?'none':holdingSort.direction}><button className="awb-sort-button" type="button" onClick={()=>toggleHoldingSort(key)} aria-label={`按${holdingSortLabels[key]}${holdingSort?.key===key&&holdingSort.direction==='ascending'?'降序':'升序'}排序`} title={`按${holdingSortLabels[key]}排序`}>{label}<span className={`awb-sort-indicator ${holdingSort?.key===key?holdingSort.direction:''}`} aria-hidden="true">↕</span></button></th>;const rows=compact?[...(snapshot?.positions??[])].sort((a,b)=>Math.abs(Number(b.marketValue))-Math.abs(Number(a.marketValue))).slice(0,overviewRows.count):sortHoldings(filtered);return <section ref={compact?overviewRows.ref:undefined} className="awb-panel awb-holdings"><div className="awb-section-heading"><h2>我的持仓 <small>{snapshot?.positions.length??0}</small></h2>{compact?<button onClick={()=>navigate('holdings')}>查看全部 <ChevronRight size={14}/></button>:<input aria-label="搜索持仓" type="search" placeholder="搜索代码 / 名称" value={search} onChange={e=>setSearch(e.target.value)}/>}</div><div className="awb-table-scroll"><table><thead><tr><th>资产</th>{compact?<th>数量 / 成本</th>:sortableHeader('quantity','数量 / 成本')}{compact?<th>市值 · {currency}</th>:sortableHeader('marketValue',<>市值 · {currency}</>)}{compact?<th>占比</th>:sortableHeader('weight','占比')}{compact?<th>券商盈亏</th>:sortableHeader('unrealizedPnl','券商盈亏')}{!compact&&<th>参考行情</th>}</tr></thead><tbody>{rows.map(p=>{const q=state?.quotes.find(q=>q.conId===p.conId),weight=nav&&nav>0&&p.currency===currency&&number(p.marketValue)!==null?Number(p.marketValue)/nav:null;return <tr key={p.conId}><td><button className="awb-symbol" onClick={()=>setSelected(p.conId)}><HoldingLogo holding={p}/><span><b>{p.symbol}</b><small>{p.name??p.symbol} · {p.instrumentType==='ETF'?'ETF':p.sector??'行业待核实'}</small></span></button></td><td>{formatQuantity(p.quantity)}<small>{money(p.averageCost)}</small></td><td>{money(p.marketValue)}<small>{p.currency}</small></td><td>{pct(weight)}<div className="awb-weight"><i style={{width:`${Math.min(100,Math.abs(weight??0)*100)}%`}}/></div></td><td className={(number(p.unrealizedPnl)??0)<0?'negative':'positive'}>{money(p.unrealizedPnl)}</td>{!compact&&<td>{money(q?.price)}<small>{q?quoteLabels[q.status]:'未取得'} · {q?.source??'东方财富'}<br/>{q?.asOf?time(q.asOf):'时间未取得'}</small></td>}</tr>;})}</tbody></table></div>{!(compact?snapshot?.positions.length:filtered.length)&&<div className="awb-empty"><p>{ready?'当前没有匹配持仓':'真实持仓将在授权并同步成功后显示'}</p><small>数量与账面金额来自 IBKR；参考行情单独展示。</small></div>}</section>;};
  return <main className={`account-workbench ${tab==='overview'?'awb-overview-compact':''} ${menu?'awb-menu-open':''}`} data-testid="ibkr-workbench"><aside className="awb-sidebar"><Link className="awb-brand" to="/"><span>SF</span><b>SparkFlow<small>ACCOUNT INTELLIGENCE</small></b></Link><nav aria-label="账户工作台导航">{navItems.map(([key,label,Icon])=><button key={key} aria-current={tab===key?'page':undefined} title={label} onClick={()=>navigate(key)}><Icon size={21}/><span>{label}</span>{key==='alerts'&&alerts.some(a=>!a.read)&&<i className="awb-dot"/>}</button>)}</nav><Link to="/" className="awb-terminal-link"><ArrowUpRight size={18}/><span>返回终端大屏</span></Link><div className="awb-sidebar-foot"><ShieldCheck size={16}/><span>IBKR · 只读账户</span></div></aside><div className="awb-body"><header className="awb-topbar"><button className="awb-menu" aria-label="展开导航" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><small>SPARKFLOW / IBKR</small><span className={`awb-status ${ready?'connected':''}`}><i/>{ready?'账户已同步':snapshot?.state==='stale'?'快照已过期':state?.connection.authorized?'已授权 · 持仓待同步':'等待账户连接'}</span></header><div className="awb-page-heading"><div><h1>{titles[tab]}</h1><p>{subtitles[tab]}</p></div><div className="awb-heading-actions"><button disabled={!!busy} onClick={()=>void act('sync','sync')} aria-label="刷新账户"><RefreshCw size={16} className={busy==='sync'?'awb-spin':''}/><span>刷新账户</span></button>{tab!=='settings'&&<button className="primary" disabled={!snapshot?.snapshotId||exporting} onClick={()=>void exportAccountPdf()}><Download size={17}/>{exporting?'正在导出 PDF':'导出 PDF'}</button>}</div></div>
  {error&&<div className="awb-message error" role="alert">{error}<button aria-label="关闭错误" onClick={()=>setError('')}><X size={15}/></button></div>}{state&&!ready&&<div className="awb-message"><ShieldCheck size={18}/><div><b>{snapshot?.snapshotId?'显示最后成功快照':state.connection.authorized?'IBKR 已授权，持仓尚未同步':'连接你的 IBKR 账户'}</b><p>{state.connection.detail}</p></div><button onClick={()=>navigate('settings')}>查看连接</button></div>}
  {!state&&<div className="awb-empty">正在载入账户工作台…</div>}{state&&<><div className="awb-provenance"><span>授权 {state.source==='gateway'?(ready?'本机只读会话':'待连接'):state.connection.authorized?'有效':'待连接'} · 账户 {time(snapshot?.asOf)}</span><span>行情 {time(state.quotes.filter(q=>q.asOf).map(q=>q.asOf!).sort().slice(-1)[0])}</span><span>研究 {time(latest?.generatedAt)}</span></div>{tab!=='overview'&&tab!=='holdings'&&<div className="awb-research-strip">{task&&task.state!=='completed'&&<div className="awb-job-select"><label>分析任务 <select aria-label="研究任务" value={task.id} disabled={!!running} onChange={e=>setSelectedJobId(e.target.value)}>{state.jobs.filter(j=>j.state!=='completed').map(j=><option key={j.id} value={j.id}>{time(j.startedAt)} · {{running:'分析中',partial:'未完成',cancelled:'已取消',failed:'未完成',interrupted:'已中断'}[j.state as 'partial']}</option>)}</select></label></div>}{task&&task.state!=='completed'&&<section className="awb-research-progress"><div><b>{running?running.progress?.stage??'单次账户分析进行中':task.error??'分析尚未完成'}</b><small>{task.progress?.strategy==='portfolio'?'完整账户已纳入':'旧任务数据'} {task.progress?.covered.length??0}/{task.progress?.total??snapshot?.positions.length??0} · 资料 {task.progress?.sources??0} · AI 调用 {task.progress?.modelCalls??0}/1 · 今日 {state.ai.usedToday}/{state.preferences.maxAiCalls}</small></div><button disabled={!!busy||(!running&&(!state.ai.enabled||state.ai.usedToday>=state.preferences.maxAiCalls))} onClick={()=>void act('job',running?'cancel':(task.progress?.modelCalls??0)===0?'resume':'analyze',running||task.progress?.modelCalls===0?{id:task.id}:{})}>{running?'取消分析':(task.progress?.modelCalls??0)===0?'继续准备并单次分析':'重新发起单次分析'}</button></section>}
  {task&&task.state!=='completed'&&<ResearchDetails key={task.id} id={task.id}/>}</div>}
  {tab==='overview'&&<><section className="awb-metrics" aria-label="账户摘要">{[['总资产',snapshot?.metrics.netLiquidation,Wallet],['未实现盈亏',snapshot?.metrics.unrealizedPnl,TrendingUp],['可用现金',cash,Wallet]].map(([label,value,Icon])=>{const I=Icon as typeof Wallet;return <article key={String(label)}><span className="awb-metric-icon"><I size={23}/></span><div><span>{String(label)}</span><strong className={label==='未实现盈亏'?(Number(value)<0?'negative':'positive'):''}>{money(value)}</strong><small>{currency} · IBKR 账面</small></div></article>;})}<article><span className="awb-metric-icon risk"><ShieldCheck size={25}/></span><div><span>规则风险等级</span><strong className="attention">{state.metrics?.riskLevel??'待计算'}</strong><details className="awb-risk-explain"><summary>{state.metrics?.reasons.length??0} 条规则触发 · 查看依据</summary>{state.metrics?.reasons.map(r=><p key={r}>{r}</p>)}</details></div></article></section><div className="awb-overview-layout"><div className="awb-overview-main"><PerformancePanel state={state}/><OverviewBrief state={state} generateBrief={()=>void act('brief','brief')} busy={!!busy||!!running} report={latest} pending={pendingReport} alerts={alerts} openReport={()=>navigate('reports')} openAlerts={()=>navigate('alerts')} openAlert={a=>{setChosenAlert(a);setChosenPlan(undefined);navigate('alerts');}}/></div><div className="awb-overview-details"><div className="awb-overview-secondary">{holdingsTable(true)}<OverviewAllocation state={state} select={p=>setSelected(p.conId)}/></div><div className="awb-overview-bottom"><OverviewPnl state={state} select={p=>setSelected(p.conId)}/><OverviewFunds state={state}/></div></div></div></>}
  {tab==='holdings'&&<>{holdingsTable(false)}<div className="awb-secondary-metrics"><span>购买力 <b>{money(snapshot?.metrics.buyingPower)} {currency}</b></span><span>维持保证金 <b>{money(snapshot?.metrics.maintenanceMargin)} {currency}</b></span><span>最大单一仓位 <b>{pct(state.metrics?.topWeight)}</b></span></div></>}
  {tab==='reports'&&<AnalysisWorkspace state={state} report={activeReport} task={task?.state==='completed'?undefined:task} running={running} busy={Boolean(busy)} canAnalyze={canAnalyze} question={question} onQuestion={setQuestion} onAsk={()=>{if(question.trim()){void act('chat','analyze',{question});setQuestion('');}}} onStart={()=>void act('analyze','analyze')} onTaskAction={job=>void act('job',job.state==='running'?'cancel':(job.progress?.modelCalls??0)===0?'resume':'analyze',job.state==='running'||(job.progress?.modelCalls??0)===0?{id:job.id}:{})} onSelectTask={setSelectedJobId} onSelect={r=>setReportId(r.id)} onPlan={()=>{setChosenAlert(undefined);setChosenPlan(undefined);setPlanReportId(activeReport?.id);navigate('alerts');}}/>}
  {tab==='alerts'&&<><div className="awb-filter">{[['all','全部'],['opportunity','机会'],['risk','风险'],['watch','已关注'],['resolved','已处理']].map(([key,label])=><button aria-pressed={filter===key} key={key} onClick={()=>setFilter(key)}>{label} <small>{state.alerts.filter(a=>key==='all'||key==='watch'&&a.watched||key==='resolved'&&a.resolved||a.kind===key).length}</small></button>)}</div><div className="awb-risk-grid"><div className="awb-stack">{state.alerts.filter(a=>filter==='all'||filter==='watch'&&a.watched||filter==='resolved'&&a.resolved||a.kind===filter).map(a=><article className={`awb-panel awb-risk-card ${a.resolved?'resolved':''} ${chosenAlert?.id===a.id?'selected':''}`} key={a.id}><span className={`awb-tag ${a.kind==='risk'?'attention':''}`}>{a.kind==='risk'?'优先关注':a.kind==='opportunity'?'机会观察':'事件提醒'}</span><h2>{a.title}</h2><p className="awb-affected">影响资产　{a.symbols.join(' · ')||'整体组合'}</p><p>{a.detail}</p>{a.trigger&&<p>触发条件　{a.trigger}</p>}<div className="awb-risk-card-actions"><small>{a.resolved?'已处理':a.read?'已读':'未读'} · {time(a.createdAt)}</small><button onClick={()=>void act('alert','alerts',{id:a.id,action:'watch'})}>{a.watched?'取消关注':'加入观察'}</button>{!a.resolved&&<button onClick={()=>void act('alert','alerts',{id:a.id,action:'resolve'})}>已处理</button>}<button className="awb-outline" onClick={()=>{setChosenAlert(a);setChosenPlan(undefined);void act('alert','alerts',{id:a.id,action:'read'});}}>查看调整计划</button></div>{a.reportId&&<button onClick={()=>{if(state.reports.some(r=>r.id===a.reportId)){setReportId(a.reportId);navigate('reports');}else void request<AnalysisReport>(`reports/${a.reportId}/json`).then(setReport).catch(()=>setError('报告暂不可用'));}}>查看证据与报告 <ArrowUpRight size={13}/></button>}</article>)}{!state.alerts.length&&<section className="awb-panel awb-empty">暂无提醒，可在右侧制定自己的计划。</section>}{!!state.plans?.length&&<section className="awb-panel"><h2>已保存计划</h2>{state.plans.map(p=><button className="awb-saved-plan" key={p.id} onClick={()=>{setChosenPlan(p);setChosenAlert(undefined);}}><span>{p.title}</span><small>{{watching:'观察中',triggered:'条件满足',handled:'已处理',invalidated:'已失效'}[p.status]}</small><ChevronRight size={14}/></button>)}</section>}</div><aside><PlanPanel key={chosenPlan?.id??chosenAlert?.id??planReportId??'new'} reportId={planReportId} state={state} alert={chosenAlert} existing={chosenPlan} onSaved={refresh}/></aside></div></>}
  {tab==='settings'&&<WorkbenchSettings state={state} busy={busy} act={act} connect={connect}/>}{tab==='alerts'&&<Chat question={question} setQuestion={setQuestion} enabled={canAnalyze} send={()=>{if(question.trim()){void act('chat','analyze',{question});setQuestion('');}}}/>}</>}
  {tab!=='overview'&&tab!=='holdings'&&<footer className="awb-footer"><span><ShieldCheck size={13}/>真实账户只读 · 操作建议由你审核</span><span>本机服务运行期间持续更新</span></footer>}</div>
  {holding&&<div className="awb-overlay" onClick={()=>setSelected(null)}><aside className="awb-drawer" role="dialog" aria-modal="true" aria-label={`${holding.symbol} 持仓详情`} onClick={e=>e.stopPropagation()}><button className="awb-close" onClick={()=>setSelected(null)} aria-label="关闭持仓详情"><X/></button><span className="awb-eyebrow">HOLDING DETAIL</span><h1>{holding.symbol}</h1><p>{holding.name} · {holding.sector??'行业待核实'} · {holding.industry}</p><div className="awb-detail-metrics"><div><small>持仓数量</small><b>{formatQuantity(holding.quantity)}</b></div><div><small>券商成本</small><b>{money(holding.averageCost)}</b></div><div><small>券商市值</small><b>{money(holding.marketValue)}</b></div></div><HoldingChart holding={holding} quote={state?.quotes.find(q=>q.conId===holding.conId)}/><Fundamentals holding={holding} report={latest}/><HoldingViews holding={holding} report={latest}/><h2>关联证据</h2>{latest?.evidence.filter(e=>e.symbols.includes(holding.symbol)).map(e=><a className="awb-detail-evidence" key={e.id} href={e.url} target="_blank" rel="noreferrer">{e.title}<small>{e.source} · 发布 {e.publishedAt?time(e.publishedAt):'未核实'}</small></a>)}</aside></div>}{report&&<ReportModal report={report} close={()=>setReport(null)}/>}</main>;
}
function Chat({ question, setQuestion, enabled, send }: { question: string; setQuestion: (v: string) => void; enabled: boolean; send: () => void }) { return <form className="awb-chat" onSubmit={e => { e.preventDefault(); send(); }}><Sparkles size={19} /><input aria-label="账户分析问题" maxLength={2000} placeholder="问问 AI：如果市场回调，我应该优先关注哪些持仓？" value={question} onChange={e => setQuestion(e.target.value)} /><button className="primary" disabled={!enabled || !question.trim()} type="submit"><ArrowUpRight size={16} />分析</button></form>; }
function WorkbenchSettings({ state, busy, act, connect }: { state: WorkbenchState; busy: string; act: (name: string, endpoint: string, data?: unknown) => Promise<void>; connect: () => Promise<void> }) {
  const [preferences, setPreferences] = useState<Preferences>(state.preferences);
  useEffect(() => setPreferences(state.preferences), [state.snapshot.accountKey]);
  const field = (key: 'targetWeight' | 'cashFloor' | 'maxDrawdown', label: string) => <label>{label}<div className="awb-input-unit"><input type="number" min="0" max="100" step="1" value={preferences[key] === null ? '' : Number((preferences[key]! * 100).toFixed(2))} placeholder="尚未设置" onChange={e => setPreferences({ ...preferences, [key]: e.target.value === '' ? null : Number(e.target.value) / 100 })} />%</div></label>;
  return <div className="awb-settings-grid"><section className="awb-panel"><h2><Link2 size={18} />账户连接</h2><p className="awb-muted">官方登录与授权在 IBKR 页面完成，密码不会进入本项目。</p><div className="awb-source-options"><button aria-pressed={state.source === 'mcp'} disabled={!!busy} onClick={() => void act('source', 'source', { source: 'mcp' })}><b>官方 MCP</b><small>网页授权 · 默认方案</small></button><button aria-pressed={state.source === 'gateway'} disabled={!!busy} onClick={() => void act('source', 'source', { source: 'gateway' })}><b>TWS / Gateway</b><small>本机客户端 · 原有只读服务</small></button></div><p className="awb-connection-detail">{state.connection.detail}</p>{state.source === 'mcp' && <><button className="primary" disabled={!!busy} onClick={() => void connect()}><Link2 size={14} />{busy === 'connect' ? '正在连接…' : '连接 / 重新授权 IBKR'}</button><button disabled={!!busy} onClick={() => void act('disconnect', 'disconnect')}>断开并清除凭据</button>{state.connection.accounts.length > 0 && <label>已授权账户<select value={state.snapshot.accountKey} onChange={e => void act('source', 'source', { source: 'mcp', accountKey: e.target.value })}><option value="live:unbound">选择账户</option>{state.connection.accounts.map(a => <option key={a.key} value={a.key}>{a.label}</option>)}</select></label>}<details className="awb-diagnostics"><summary>MCP 接入诊断</summary><p>服务器地址 https://api.ibkr.com/v1/api/mcp-public</p><p>仅申请 mcp.read 与账户标识权限。登录成功后核验工具和字段；不支持的结构会明确显示错误。</p>{state.connection.tools.map(t => <p key={t.name}><code>{t.name}</code> {t.description}</p>)}</details></>}{state.source === 'gateway' && <p>请在本机运行原有 IBKR 只读服务并登录实盘账户。账户来源不会自动切换。</p>}</section>
    <section className="awb-panel"><h2><Sparkles size={18} />AI 模型与账户数据</h2><dl className="awb-setting-dl"><div><dt>当前模型</dt><dd>{state.ai.model || '尚未配置'}</dd></div><div><dt>提供方</dt><dd>{state.ai.provider || '—'}</dd></div><div><dt>今日调用</dt><dd>{state.ai.usedToday} / {state.preferences.maxAiCalls}</dd></div></dl><div className="awb-research-services"><b>研究服务</b>{state.researchServices?.map(s=><p key={s}>{s}</p>)}<small>系统可先收集公开行情与原文；每份账户报告只把完整账户提交给 AI 一次，不做逐仓模型分析或自动修复调用。</small></div><p>复用 Vibe-Trading 模型配置。一次发送 {state.ai.fields.join('、')}，不含登录凭据和完整券商账号。</p><p className="awb-muted">模型或服务地址改变后，需重新核对并开启分析。关闭后不再发送新请求，已发送的请求无法从提供方收回。</p><button className={state.ai.enabled ? '' : 'primary'} disabled={!!busy || !state.snapshot.snapshotId || (!state.ai.configured && !state.ai.enabled)} onClick={() => void act('consent', 'consent', { enabled: !state.ai.enabled, fingerprint: state.ai.fingerprint })}>{state.ai.enabled ? '关闭账户 AI 分析' : '同意发送上述字段并开启 AI'}</button>{!state.ai.configured && <p className="awb-muted">请在项目现有 AI / Vibe-Trading 设置中配置模型后刷新。</p>}</section>
    <form className="awb-panel awb-preferences" onSubmit={e => { e.preventDefault(); void act('preferences', 'preferences', preferences); }}><h2><Settings2 size={18} />投资偏好与自动分析</h2><div className="awb-form-grid"><label>投资周期<select value={preferences.horizon} onChange={e => setPreferences({ ...preferences, horizon: e.target.value as Preferences['horizon'] })}><option value="both">短期与长期分别分析</option><option value="long">中长期配置</option><option value="swing">波段交易</option></select></label>{field('targetWeight', '单标的目标仓位上限')}{field('cashFloor', '现金占比底线')}{field('maxDrawdown', '可接受回撤')}<label>比较基准<select value={preferences.benchmark??'SPY'} onChange={e=>setPreferences({...preferences,benchmark:e.target.value as Preferences['benchmark']})}><option value="SPY">SPY</option><option value="QQQ">QQQ</option><option value="none">关闭比较</option></select></label><label>每日 AI 总调用上限<input type="number" min="1" max="100" value={preferences.maxAiCalls} onChange={e => setPreferences({ ...preferences, maxAiCalls: Number(e.target.value) })} /></label><label>每日事件分析上限<input type="number" min="0" max="24" value={preferences.maxAutomatic} onChange={e => setPreferences({ ...preferences, maxAutomatic: Number(e.target.value) })} /></label><label>事件分析间隔（分钟）<input type="number" min="15" max="1440" value={preferences.cooldownMinutes} onChange={e => setPreferences({ ...preferences, cooldownMinutes: Number(e.target.value) })} /></label></div><label className="awb-checkbox"><input type="checkbox" checked={preferences.daily} onChange={e => setPreferences({ ...preferences, daily: e.target.checked })} />每个美股交易日收盘后 30 分钟生成简短账户简报（纽约时间）</label><label className="awb-checkbox"><input type="checkbox" checked={preferences.eventAnalysis} onChange={e => setPreferences({ ...preferences, eventAnalysis: e.target.checked })} />持仓变化或新增事件触发补充分析</label><p className="awb-muted">未填写偏好时，AI 提供条件式方案。参数齐全后显示独立情景估算，金额、权重和资金由程序统一计算。电脑关机期间暂停；恢复后只补最新一期日报。</p><button className="primary" disabled={!!busy || !state.snapshot.snapshotId} type="submit">{busy === 'preferences' ? '保存中…' : '保存偏好'}</button></form></div>;
}
function HoldingViews({ report, holding }: { report?: AnalysisReport; holding: Holding }) { const view = report?.content.holdings.find(h => h.symbol === holding.symbol); return <><h2>持仓研究</h2>{view ? <><p>{view.background}</p><div className="awb-view"><b><ArrowDownLeft size={15} />短期应对</b><p>{view.shortTerm}</p></div><div className="awb-view"><b><ArrowUpRight size={15} />长期逻辑</b><p>{view.longTerm}</p></div>{report?.content.actions.filter(a => a.symbol === holding.symbol).map((a, i) => <div className="awb-action" key={i}><b>{a.horizon === 'short' ? '短期' : '长期'} · {actionLabels[a.action]}</b><p>{a.rationale}</p><small>触发条件：{a.trigger}</small><small>反对证据：{a.counterEvidence}</small><small>失效条件：{a.invalidation}</small>{a.shares !== undefined && <p>独立情景估算：{a.shares > 0 ? '+' : ''}{a.shares} 股 · 调整后现金约 {money(a.estimatedCashAfter)} USD · 仓位 {pct(a.estimatedWeightAfter)}<small>按券商快照估价，不含费用；各情景不能直接相加。</small></p>}</div>)}</> : <p className="awb-muted">生成账户深度分析后展示该持仓的短期和长期观点。</p>}</>; }
function HoldingChart({ holding, quote }: { holding: Holding; quote?: MarketQuote }) {
  const [period, setPeriod] = useState('1M'); const [bars, setBars] = useState<{ time: string; close: number }[]>([]); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); setBars([]); setError(''); request<{ bars: { time: string; close: number }[] }>(`history?conId=${holding.conId}&period=${period}`, undefined, controller.signal).then(data => setBars(data.bars)).catch(e => { if (e.name !== 'AbortError') setError(e.message); }); return () => controller.abort(); }, [holding.conId, period]);
  const low = Math.min(...bars.map(b => b.close)), high = Math.max(...bars.map(b => b.close));
  const points = bars.map((b, i) => `${20 + i / Math.max(1, bars.length - 1) * 600},${170 - (b.close - low) / Math.max(0.01, high - low) * 140}`).join(' ');
  return <section className="awb-chart"><div className="awb-section-heading"><h2>参考行情 {money(quote?.price)}</h2><div>{['1D', '5D', '1M', '6M', '1Y'].map(p => <button aria-pressed={period === p} onClick={() => setPeriod(p)} key={p}>{p}</button>)}</div></div>{bars.length ? <><svg viewBox="0 0 640 200" role="img" aria-label={`${holding.symbol} 历史收盘价曲线`}><path d="M20 30H620M20 100H620M20 170H620" stroke="#233936" fill="none" /><polyline points={points} fill="none" stroke="#66d8b9" strokeWidth="2" /></svg><div className="awb-chart-labels"><span>{bars[0].time}</span><span>{bars[bars.length - 1].time}</span></div></> : <div className="awb-empty">{error || '历史行情载入中…'}</div>}<small>东方财富 · 不复权 · 上游时间原样展示 · {quote ? quoteLabels[quote.status] : '报价未取得'} · 报价时间 {time(quote?.asOf)}</small></section>;
}
function ReportModal({ report, close }: { report: AnalysisReport; close: () => void }) { const [error, setError] = useState(''); const [exporting, setExporting] = useState(false); return <div className="awb-overlay" onClick={close}><section className="awb-report-modal" role="dialog" aria-modal="true" aria-label="账户分析报告" onClick={e => e.stopPropagation()}><header><b>SparkFlow · 账户研究</b><div><a href={`${api}reports/${report.id}/html`}><Download size={14} /> HTML</a><button disabled={exporting} onClick={async () => { setExporting(true); try { await exportSparkFlowResearchPdf(reportMarkdown(report)); } catch { setError('PDF 导出失败，请尝试 HTML 下载'); } finally { setExporting(false); } }}><Download size={14} />{exporting ? '生成中…' : 'PDF'}</button><button aria-label="关闭报告" onClick={close}><X size={20} /></button></div></header>{error && <p role="alert">{error}</p>}<article className="awb-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{reportMarkdown(report)}</ReactMarkdown></article></section></div>; }

function Fundamentals({holding,report}:{holding:Holding;report?:AnalysisReport}){const e=report?.evidence.find(e=>e.symbols.includes(holding.symbol)&&e.kind==='profile');let data:any;try{data=JSON.parse(e?.content??'{}');}catch{}const val=(v:any)=>v?.raw??v;return <section className="awb-fundamentals"><h2>基本面快照</h2><div className="awb-detail-metrics">{[['远期市盈率',val(data?.statistics?.forwardPE)],['收入同比',val(data?.financials?.revenueGrowth)],['净利润率',val(data?.financials?.profitMargins)]].map(([label,v])=><div key={label}><small>{label}</small><b>{label==='远期市盈率'?money(v):pct(number(v))}</b></div>)}</div><small>{e?`${e.source} · 获取 ${time(e.fetchedAt)} · 财务报告期以原始来源为准`:'尚未取得基本面原始数据；深度研究后更新。'}</small></section>;}
