import { useEffect, useMemo, useState } from 'react';
import { Ban, Download, FileUp, Play, RefreshCw, Save, ShieldCheck } from 'lucide-react';
import type { BacktestInputBar, BacktestJob, BacktestPackage, BacktestResult, BacktestStrategy, BacktestStrategyDefinition, Holding } from '../../lib/ibkr/workbenchTypes';
import './BacktestWorkspace.css';

const api = '/api/ibkr-workbench/';
async function call<T>(endpoint:string,value?:unknown):Promise<T>{const response=await fetch(api+endpoint,{...(value===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'回测服务暂不可用');return data;}
const decimal=/^(0|[1-9]\d{0,17})(\.\d{1,18})?$/;
const isoOffset=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;
const text=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?String(value):typeof value==='string'?value.trim():'';
const money=(value:unknown)=>Number.isFinite(Number(value))?Number(value).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const pct=(value:unknown)=>Number.isFinite(Number(value))?`${(Number(value)*100).toFixed(2)}%`:'—';
const time=(value:string)=>new Date(value).toLocaleString('zh-CN',{hour12:false});

function normalizeRows(value:unknown):BacktestInputBar[]{
  const rows:unknown[]|null=Array.isArray(value)?value:Array.isArray((value as any)?.bars)?(value as any).bars as unknown[]:null;
  if(!rows||rows.length<2||rows.length>100000)throw new Error('历史数据必须包含 2–100,000 根 bar。');
  const allowed=new Set(['timestamp','open','high','low','close','volume','splitRatio','dividendPerShare']);
  const normalized:BacktestInputBar[]=rows.map((raw:unknown,index:number)=>{
    if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(key=>!allowed.has(key)))throw new Error(`第 ${index+1} 行包含不支持的字段。`);
    const timestamp=text((raw as any).timestamp),open=text((raw as any).open),high=text((raw as any).high),low=text((raw as any).low),close=text((raw as any).close);
    if(!isoOffset.test(timestamp)||![open,high,low,close].every(item=>decimal.test(item)))throw new Error(`第 ${index+1} 行时间或 OHLC 无效。时间必须包含 Z 或时区。`);
    const optional=(key:string)=>{const item=(raw as any)[key];return item===null||item===undefined||item===''?null:text(item);};
    const volume=optional('volume'),splitRatio=optional('splitRatio'),dividendPerShare=optional('dividendPerShare')??'0';
    if((volume!==null&&!decimal.test(volume))||(splitRatio!==null&&!decimal.test(splitRatio))||!decimal.test(dividendPerShare))throw new Error(`第 ${index+1} 行成交量或公司行动字段无效。`);
    return {timestamp,open,high,low,close,volume,splitRatio,dividendPerShare};
  });
  const epochs:number[]=normalized.map((row:BacktestInputBar)=>Date.parse(row.timestamp));
  if(epochs.some((value:number,index:number)=>!Number.isFinite(value)||(index>0&&value<=epochs[index-1])))throw new Error('历史 bar 必须按时间严格递增，不能重复或倒序。');
  return normalized;
}

function parseCsv(raw:string){
  const lines=raw.replace(/^\uFEFF/,'').split(/\r?\n/).filter(line=>line.trim());
  if(lines.length<3)throw new Error('CSV 至少需要表头和两行数据。');
  const headers=lines[0].split(',').map(value=>value.trim());
  return normalizeRows(lines.slice(1).map(line=>{const values=line.split(',').map(value=>value.trim());if(values.length!==headers.length)throw new Error('CSV 列数不一致；暂不支持带逗号的文本列。');return Object.fromEntries(headers.map((key,index)=>[key,values[index]||null]));}));
}

function EquityMiniChart({result}:{result:BacktestResult}){
  const points=result.equityCurve.map(row=>Number(row.equity)).filter(Number.isFinite);if(points.length<2)return <div className="awb-backtest-chart-empty">权益点不足，无法绘图</div>;
  const min=Math.min(...points),max=Math.max(...points),span=max-min||1,path=points.map((value,index)=>`${index?'L':'M'} ${index/(points.length-1)*1000} ${180-(value-min)/span*150}`).join(' ');
  return <svg className="awb-backtest-chart" viewBox="0 0 1000 200" preserveAspectRatio="none" role="img" aria-label="回测权益曲线"><path d={`${path} L 1000 190 L 0 190 Z`} className="area"/><path d={path} className="line"/></svg>;
}

export function BacktestWorkspace({holdings}:{holdings:Holding[]}){
  const [strategies,setStrategies]=useState<BacktestStrategy[]>([]),[jobs,setJobs]=useState<BacktestJob[]>([]),[runs,setRuns]=useState<BacktestResult[]>([]),[selectedRun,setSelectedRun]=useState<BacktestResult|null>(null);
  const [busy,setBusy]=useState(''),[error,setError]=useState(''),[bars,setBars]=useState<BacktestInputBar[]>([]),[fileName,setFileName]=useState(''),[actionsComplete,setActionsComplete]=useState(false);
  const [form,setForm]=useState({slug:'my-sma',version:'1.0.0',name:'我的 SMA 规则',conId:String(holdings[0]?.conId??''),fast:'5',slow:'20',quantity:'10',maxQuantity:'10',commissionOrder:'0',commissionShare:'0',slippage:'5',notes:'本人录入的结构化回测规则；仅用于回测，不授予交易权限。'});
  const [selectedStrategy,setSelectedStrategy]=useState(''),[initialCash,setInitialCash]=useState('100000');
  const refresh=async()=>{const [nextStrategies,nextJobs,nextRuns]=await Promise.all([call<BacktestStrategy[]>('backtests/strategies'),call<BacktestJob[]>('backtests/jobs'),call<BacktestResult[]>('backtests/runs')]);setStrategies(nextStrategies);setJobs(nextJobs);setRuns(nextRuns);setSelectedStrategy(current=>current||(nextStrategies[0]?`${nextStrategies[0].definition.strategyId}@${nextStrategies[0].definition.version}`:''));setSelectedRun(current=>current?nextRuns.find(run=>run.runHash===current.runHash)??current:nextRuns[0]??null);};
  useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:'回测服务暂不可用'));},[]);
  useEffect(()=>{if(!jobs.some(job=>['PENDING','RUNNING','CANCEL_REQUESTED'].includes(job.state)))return;const timer=setInterval(()=>void refresh().catch(()=>{}),1500);return()=>clearInterval(timer);},[jobs]);
  const canSave=useMemo(()=>Boolean(form.name.trim()&&form.notes.trim())&&/^[-A-Za-z0-9:_]+$/.test(form.slug)&&/^\d+\.\d+\.\d+$/.test(form.version)&&Number(form.conId)>0&&Number.isInteger(Number(form.conId))&&Number(form.fast)>0&&Number(form.slow)>Number(form.fast)&&Number(form.quantity)>0&&Number.isInteger(Number(form.quantity))&&Number(form.maxQuantity)>=Number(form.quantity)&&[form.commissionOrder,form.commissionShare,form.slippage].every(value=>decimal.test(value)),[form]);
  const strategyKey=(value:BacktestStrategy)=>`${value.definition.strategyId}@${value.definition.version}`;
  const save=async()=>{if(!canSave)return;setBusy('save');setError('');try{const fast=Number(form.fast),slow=Number(form.slow),definition:BacktestStrategyDefinition={strategyId:`user:${form.slug.replace(/^user:/,'')}`,version:form.version,origin:'user',name:form.name,universe:[Number(form.conId)],barInterval:'1D',entryRule:`${fast} 日简单移动平均线高于 ${slow} 日简单移动平均线时，在下一根 bar 开盘建立目标仓位。`,exitRule:`${fast} 日简单移动平均线不高于 ${slow} 日简单移动平均线时，在下一根 bar 开盘退出。`,parameters:{fastWindow:String(fast),slowWindow:String(slow),targetQuantity:form.quantity},signal:{kind:'sma_cross',priceField:'close',fastWindow:fast,slowWindow:slow,entryWhen:'FAST_ABOVE_SLOW',exitWhen:'FAST_AT_OR_BELOW_SLOW'},positionSizing:{kind:'fixed_quantity',targetQuantity:form.quantity},costs:{commissionPerOrder:form.commissionOrder,commissionPerShare:form.commissionShare,slippageBps:form.slippage},risk:{allowShort:false,maxPositionQuantity:form.maxQuantity},versionNotes:form.notes};const saved=await call<BacktestStrategy>('backtests/strategies',definition);await refresh();setSelectedStrategy(strategyKey(saved));}catch(e){setError(e instanceof Error?e.message:'策略保存失败');}finally{setBusy('');}};
  const loadFile=async(file?:File)=>{if(!file)return;setError('');setBars([]);setFileName(file.name);try{if(file.size>3.5*1024*1024)throw new Error('数据文件超过 3.5 MB。');const raw=await file.text();setBars(file.name.toLowerCase().endsWith('.csv')?parseCsv(raw):normalizeRows(JSON.parse(raw)));}catch(e){setFileName('');setError(e instanceof Error?e.message:'无法读取历史数据');}};
  const run=async()=>{if(!selectedStrategy||!bars.length||!actionsComplete||!decimal.test(initialCash)||Number(initialCash)<=0)return;const [strategyId,strategyVersion]=selectedStrategy.split('@');setBusy('run');setError('');try{await call<BacktestJob>('backtests/run',{strategyId,strategyVersion,initialCash,corporateActionsComplete:true,bars});await refresh();}catch(e){setError(e instanceof Error?e.message:'回测启动失败');}finally{setBusy('');}};
  const cancel=async(jobId:string)=>{setBusy(jobId);setError('');try{await call('backtests/cancel',{jobId});await refresh();}catch(e){setError(e instanceof Error?e.message:'取消失败');}finally{setBusy('');}};
  const exportPackage=async(runHash:string)=>{setBusy('export');setError('');try{const value=await call<BacktestPackage>(`backtests/package?runHash=${runHash}`);const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`sparkflow-backtest-${runHash}.json`;anchor.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:'导出失败');}finally{setBusy('');}};
  const active=jobs.filter(job=>['PENDING','RUNNING','CANCEL_REQUESTED'].includes(job.state));
  return <div className="awb-backtest" data-testid="backtest-workspace">
    {error&&<div className="awb-message error" role="alert"><span>{error}</span></div>}
    <section className="awb-backtest-notice"><ShieldCheck/><div><b>结构化回测不会发送订单</b><p>仅运行固定 SMA 规则；不加载用户代码。保存策略和回测结果不等于模拟盘或实盘交易授权。</p></div><button onClick={()=>void refresh()} disabled={!!busy}><RefreshCw size={15}/>刷新</button></section>
    <div className="awb-backtest-grid">
      <section className="awb-panel awb-backtest-editor"><div className="awb-section-heading"><h2>1. 保存策略版本</h2><small>用户策略 · 版本不可覆盖</small></div>
        <div className="awb-backtest-fields"><label>策略标识<span><i>user:</i><input aria-label="策略标识" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></span></label><label>版本<input aria-label="策略版本" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label>名称<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>IBKR conId<input inputMode="numeric" value={form.conId} onChange={e=>setForm({...form,conId:e.target.value})}/></label><label>快均线<input inputMode="numeric" value={form.fast} onChange={e=>setForm({...form,fast:e.target.value})}/></label><label>慢均线<input inputMode="numeric" value={form.slow} onChange={e=>setForm({...form,slow:e.target.value})}/></label><label>目标股数<input inputMode="numeric" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>最大持仓股数<input inputMode="numeric" value={form.maxQuantity} onChange={e=>setForm({...form,maxQuantity:e.target.value})}/></label><label>每单佣金 USD<input value={form.commissionOrder} onChange={e=>setForm({...form,commissionOrder:e.target.value})}/></label><label>每股佣金 USD<input value={form.commissionShare} onChange={e=>setForm({...form,commissionShare:e.target.value})}/></label><label>滑点 bps<input value={form.slippage} onChange={e=>setForm({...form,slippage:e.target.value})}/></label></div>
        {!!holdings.length&&<label>从当前持仓选择<select value="" onChange={e=>setForm({...form,conId:e.target.value})}><option value="">选择后填入 conId</option>{holdings.filter(row=>row.currency==='USD'&&row.assetType==='STK').map(row=><option key={row.conId} value={row.conId}>{row.symbol} · {row.conId}</option>)}</select></label>}
        <label>版本说明<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="awb-backtest-rule"><b>规则预览</b><p>{form.fast} 日 SMA 高于 {form.slow} 日 SMA 后，下一根 bar 开盘持有 {form.quantity} 股；否则下一根 bar 退出。禁止做空。</p></div><button className="primary" disabled={!canSave||!!busy} onClick={()=>void save()}><Save size={15}/>{busy==='save'?'保存中':'保存不可变版本'}</button>
      </section>
      <section className="awb-panel awb-backtest-runner"><div className="awb-section-heading"><h2>2. 导入数据并回测</h2><small>后台运行 · 账户刷新不受阻</small></div><label>策略版本<select aria-label="回测策略" value={selectedStrategy} onChange={e=>setSelectedStrategy(e.target.value)}><option value="">先保存用户策略</option>{strategies.map(strategy=><option key={strategy.strategyHash} value={strategyKey(strategy)}>{strategy.definition.name} · {strategy.definition.version}</option>)}</select></label><label>初始资金 USD<input value={initialCash} onChange={e=>setInitialCash(e.target.value)}/></label><label className="awb-backtest-upload"><FileUp/><b>{fileName||'选择历史数据 JSON / CSV'}</b><small>timestamp, open, high, low, close, volume, splitRatio, dividendPerShare</small><input aria-label="上传回测数据" type="file" accept=".json,.csv,application/json,text/csv" onChange={e=>void loadFile(e.target.files?.[0])}/></label>{bars.length>0&&<div className="awb-backtest-data"><b>{bars.length.toLocaleString()} 根 bar</b><span>{bars[0].timestamp} → {bars[bars.length-1]?.timestamp}</span><small>来源将在服务端固定记录为 user.upload，并生成数据哈希。</small></div>}<label className="awb-checkbox"><input type="checkbox" checked={actionsComplete} onChange={e=>setActionsComplete(e.target.checked)}/><span>我确认数据中的拆分比例和每股分红完整；缺失公司行动会使收益失真。</span></label><button className="primary" disabled={!selectedStrategy||!bars.length||!actionsComplete||!decimal.test(initialCash)||Number(initialCash)<=0||!!busy} onClick={()=>void run()}><Play size={15}/>{busy==='run'?'正在创建任务':'启动可复现回测'}</button>
        <div className="awb-backtest-jobs"><h3>任务</h3>{jobs.slice(0,8).map(job=><div key={job.jobId}><span className={`state ${job.state.toLowerCase()}`}>{job.state}</span><small>{time(job.createdAt)}{job.errorCode?` · ${job.errorCode}`:''}</small>{['PENDING','RUNNING','CANCEL_REQUESTED'].includes(job.state)&&<button disabled={!!busy} onClick={()=>void cancel(job.jobId)}><Ban size={13}/>取消</button>}</div>)}{!jobs.length&&<p>尚无回测任务</p>}</div>{active.length>0&&<small>当前 {active.length} 个任务正在后台处理。</small>}
      </section>
    </div>
    <section className="awb-panel awb-backtest-results"><div className="awb-section-heading"><h2>3. 回测结果</h2><div><select aria-label="回测结果" value={selectedRun?.runHash??''} onChange={e=>setSelectedRun(runs.find(run=>run.runHash===e.target.value)??null)}><option value="">选择结果</option>{runs.map(run=><option key={run.runHash} value={run.runHash}>{run.strategyId} · {time(run.startedAt)}</option>)}</select>{selectedRun&&<button disabled={!!busy} onClick={()=>void exportPackage(selectedRun.runHash)}><Download size={14}/>导出完整包</button>}</div></div>{selectedRun?<><div className="awb-backtest-metrics">{[['总收益率',pct(selectedRun.metrics.totalReturn)],['最终权益',money(selectedRun.metrics.finalEquity)],['最大回撤',pct(selectedRun.metrics.maxDrawdown)],['基准收益',pct(selectedRun.metrics.benchmarkReturn)],['成交次数',String(selectedRun.metrics.tradeCount)],['费用',money(selectedRun.metrics.totalFees)]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><EquityMiniChart result={selectedRun}/><div className="awb-table-scroll"><table><thead><tr><th>执行时间</th><th>方向</th><th>数量</th><th>原始开盘价</th><th>含滑点价格</th><th>费用</th></tr></thead><tbody>{selectedRun.executions.map((row,index)=><tr key={`${row.executedAt}-${index}`}><td>{time(row.executedAt)}</td><td>{row.side}</td><td>{row.quantity}</td><td>{row.rawPrice}</td><td>{row.price}</td><td>{row.fee}</td></tr>)}</tbody></table></div><p className="awb-backtest-hashes">策略 {selectedRun.strategyHash}<br/>数据 {selectedRun.datasetHash}<br/>配置 {selectedRun.configHash}<br/>运行 {selectedRun.runHash}</p></>:<div className="awb-empty"><p>尚无已完成回测</p><small>结果会保存策略、数据、配置和运行哈希，可重复校验。</small></div>}</section>
  </div>;
}
