import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, CircleStop, RefreshCw, Search, ShieldCheck, ShoppingCart, X } from 'lucide-react';
import type { PaperContract, PaperOrderPreview, PaperOrderRecord, PaperRiskLimits, PaperStatus, WorkbenchState } from '../../lib/ibkr/workbenchTypes';

const api = '/api/ibkr-workbench/paper/';
async function paperRequest<T>(endpoint: string, value?: unknown): Promise<T> {
  const response = await fetch(api + endpoint, value === undefined ? {} : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || '模拟盘订单服务暂不可用');
  return data;
}

const errors: Record<string,string> = {
  PAPER_GATEWAY_READONLY: 'IB Gateway 仍处于“只读 API”模式。请在 Gateway「配置 → API → 设置」取消“只读 API”，应用并重启 Gateway，再点智能连接。',
  PAPER_ACCOUNT_UNAVAILABLE: '模拟盘账户连接不可用，请确认登录的是 Simulated Trading，并重新智能连接。',
  PAPER_EXECUTION_DISABLED: '模拟盘交易授权尚未开启或已经停止。',
  PAPER_POLICY_ALREADY_CONFIGURED: '本次运行已设置交易范围；如需修改，请重启本地桥接后重新授权。',
  PAPER_POLICY_EXPIRY: '授权有效期必须在当前时间之后且不超过 8 小时。',
  PREVIEW_EXPIRED: '订单预览已过期，请重新预览。',
  PREVIEW_BODY_CHANGED: '订单内容与预览不一致，已拒绝发送。',
  STALE_QUOTE: '券商行情已过期，无法新增风险。',
  QUOTE_NOT_REALTIME: '当前不是 IBKR 实时行情，无法通过下单风控。',
  ACCOUNT_STALE: '账户快照已过期，请先刷新并对账。',
  RECONCILIATION_REQUIRED: '订单状态不确定，必须先对账，禁止盲目重试。',
};
const message = (error: unknown) => { const raw = error instanceof Error ? error.message : 'PAPER_OPERATION_FAILED'; return errors[raw] ?? raw; };
const initialLimits: Record<keyof PaperRiskLimits,string> = { maxOrderNotional:'', maxTotalExposure:'', maxSymbolWeight:'', maxDailyLoss:'', maxDailyOrders:'', maxOrdersPerMinute:'', maxQuoteAgeSeconds:'5', maxAccountAgeSeconds:'20', maxPriceDeviation:'', feeReserve:'' };

export function PaperTradingWorkspace({ state, openSettings }: { state: WorkbenchState; openSettings: () => void }) {
  const [status,setStatus]=useState<PaperStatus|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const [symbol,setSymbol]=useState(''); const [found,setFound]=useState<PaperContract[]>([]); const [contracts,setContracts]=useState<PaperContract[]>([]);
  const [limits,setLimits]=useState(initialLimits); const [hours,setHours]=useState('1');
  const [order,setOrder]=useState({conId:'',side:'BUY' as 'BUY'|'SELL',quantity:'',limitPrice:''}); const [preview,setPreview]=useState<PaperOrderPreview|null>(null); const [cancelOrder,setCancelOrder]=useState<PaperOrderRecord|null>(null);
  const selected=contracts.find(row=>String(row.conId)===order.conId);
  const load=useCallback(async()=>{try{setStatus(await paperRequest<PaperStatus>('status'));setError('');}catch(e){setError(message(e));}},[]);
  useEffect(()=>{if(state.source!=='gateway'||state.gatewayMode!=='paper')return;void load();const timer=setInterval(()=>void load(),4000);return()=>clearInterval(timer);},[state.source,state.gatewayMode,load]);
  const execute=async(name:string,run:()=>Promise<void>)=>{if(busy)return;setBusy(name);setError('');try{await run();}catch(e){setError(message(e));}finally{setBusy('');}};
  const search=()=>execute('search',async()=>{const rows=await paperRequest<PaperContract[]>('contract',{symbol});setFound(rows);if(!rows.length)setError('IBKR 未找到对应的美股或 ETF 合约。');});
  const add=(row:PaperContract)=>{setContracts(current=>current.some(item=>item.conId===row.conId)?current:[...current,row]);setFound([]);setSymbol('');setOrder(current=>({...current,conId:String(row.conId)}));};
  const parsedLimits=useMemo(()=>{const percent=(v:string)=>{const n=Number(v);return Number.isFinite(n)?String(n/100):'';};return {maxOrderNotional:limits.maxOrderNotional,maxTotalExposure:limits.maxTotalExposure,maxSymbolWeight:percent(limits.maxSymbolWeight),maxDailyLoss:limits.maxDailyLoss,maxDailyOrders:Number(limits.maxDailyOrders),maxOrdersPerMinute:Number(limits.maxOrdersPerMinute),maxQuoteAgeSeconds:Number(limits.maxQuoteAgeSeconds),maxAccountAgeSeconds:Number(limits.maxAccountAgeSeconds),maxPriceDeviation:percent(limits.maxPriceDeviation),feeReserve:limits.feeReserve} as PaperRiskLimits;},[limits]);
  const canConfigure=contracts.length>0&&Number(hours)>0&&Number(hours)<=8&&Object.values(limits).every(Boolean)&&Object.values(parsedLimits).every(value=>typeof value==='number'?Number.isFinite(value):Boolean(value));
  const configure=()=>execute('configure',async()=>{const expiresAt=new Date(Date.now()+Number(hours)*3600000).toISOString();setStatus(await paperRequest<PaperStatus>('configure',{conIds:contracts.map(c=>c.conId),expiresAt,limits:parsedLimits,explicit:true}));});
  const makePreview=()=>execute('preview',async()=>{setPreview(await paperRequest<PaperOrderPreview>('preview',{conId:Number(order.conId),side:order.side,quantity:order.quantity,limitPrice:order.limitPrice}));});
  const confirm=()=>execute('confirm',async()=>{if(!preview)return;await paperRequest('confirm',{previewId:preview.previewId,bodyHash:preview.bodyHash,explicit:true});setPreview(null);setOrder(current=>({...current,quantity:'',limitPrice:''}));await load();});
  const cancel=()=>execute('cancel',async()=>{if(!cancelOrder)return;await paperRequest('cancel',{intentId:cancelOrder.intent.clientIntentId,bodyHash:cancelOrder.bodyHash,explicit:true});setCancelOrder(null);await load();});
  const paperSelected=state.source==='gateway'&&state.gatewayMode==='paper';
  if(!paperSelected)return <section className="awb-panel awb-paper-blocked"><ShoppingCart/><h2>仅支持 IB Gateway 模拟盘</h2><p>切换到模拟盘账户后，这里才会显示授权、预览、确认和撤单功能。</p><button className="primary" onClick={openSettings}>前往连接设置</button></section>;
  return <div className="awb-paper-workspace">
    {error&&<div className="awb-message error" role="alert"><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}><X size={15}/></button></div>}
    <section className={`awb-paper-banner ${status?.available?'ready':'blocked'}`}><span><ShieldCheck/></span><div><small>PAPER EXECUTION CHANNEL</small><h2>{status?.available?(status.enabled?'模拟盘交易已授权':'模拟盘通道可用，等待交易范围授权'):'模拟盘当前仍是只读连接'}</h2><p>{status?.available?'所有订单均先预览并重新校验风控，确认后只发送到当前模拟账户。':'读取持仓已连接；下单还需要取消 Gateway 的“只读 API”设置并重启连接。'}</p></div><button onClick={()=>void load()} disabled={!!busy}><RefreshCw size={15}/>刷新状态</button></section>
    {!status?.available&&<section className="awb-panel awb-paper-setup"><h2><AlertTriangle size={18}/>启用模拟盘订单通道</h2><ol><li>确认 Gateway 标题或登录页显示“模拟交易”。</li><li>打开「配置 → API → 设置」，取消勾选“只读 API”并应用。</li><li>点击下方按钮，SparkFlow 会重新核对同一个模拟账户并切换订单连接。</li></ol><p>这个动作不会发送订单；实盘 Gateway 始终被代码强制为只读。</p><button className="primary" disabled={!!busy} onClick={()=>execute('transport',async()=>{await paperRequest('transport',{explicit:true});await load();})}>{busy==='transport'?'正在重连模拟盘…':'我已取消只读，启用模拟盘订单连接'}</button> <button onClick={openSettings}>打开连接设置</button></section>}
    {status?.available&&!status.enabled&&<section className="awb-panel"><div className="awb-section-heading"><h2>1. 授权标的与风险上限</h2><small>本次授权最长 8 小时，服务重启后失效</small></div><div className="awb-paper-search"><input aria-label="搜索模拟盘合约" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} onKeyDown={e=>{if(e.key==='Enter')void search();}} placeholder="输入美股 / ETF 代码，如 AAPL"/><button disabled={!symbol||!!busy} onClick={()=>void search()}><Search size={15}/>{busy==='search'?'查询中':'查询 IBKR 合约'}</button></div>{found.length>0&&<div className="awb-paper-contract-results">{found.map(row=><button key={row.conId} onClick={()=>add(row)}><b>{row.symbol}</b><span>{row.name||'IBKR 合约'} · {row.exchange||'SMART'} · {row.currency}</span><small>conId {row.conId}</small></button>)}</div>}<div className="awb-paper-chips">{contracts.map(row=><span key={row.conId}>{row.symbol}<button aria-label={`移除 ${row.symbol}`} onClick={()=>setContracts(current=>current.filter(c=>c.conId!==row.conId))}><X size={12}/></button></span>)}</div><div className="awb-paper-risk-grid">{([
      ['maxOrderNotional','单笔最大名义金额','USD'],['maxTotalExposure','账户最大总敞口','USD'],['maxSymbolWeight','单一标的最大权重','%'],['maxDailyLoss','当日最大亏损','USD'],['maxDailyOrders','每日最大订单数','笔'],['maxOrdersPerMinute','每分钟最大订单数','笔'],['maxPriceDeviation','限价偏离行情上限','%'],['feeReserve','手续费预留','USD'],['maxQuoteAgeSeconds','行情最大年龄','秒'],['maxAccountAgeSeconds','账户快照最大年龄','秒']
    ] as const).map(([key,label,unit])=><label key={key}>{label}<span><input inputMode="decimal" value={limits[key]} onChange={e=>setLimits(current=>({...current,[key]:e.target.value}))}/><i>{unit}</i></span></label>)}<label>授权有效期<span><input inputMode="decimal" value={hours} onChange={e=>setHours(e.target.value)}/><i>小时</i></span></label></div><div className="awb-paper-consent"><ShieldCheck size={17}/><p>点击后表示你明确授权当前模拟账户、上述合约与风险上限。它不授权实盘、期权、做空、杠杆或自动策略。</p><button className="primary" disabled={!canConfigure||!!busy} onClick={()=>void configure()}>{busy==='configure'?'正在开启':'开启本次模拟盘交易'}</button></div></section>}
    {status?.enabled&&<><section className="awb-panel"><div className="awb-section-heading"><h2>1. 新订单</h2><small>美股 / ETF · 整股 · 限价单 · DAY · 常规时段</small></div><div className="awb-paper-order-form"><label>合约<select value={order.conId} onChange={e=>{setOrder(current=>({...current,conId:e.target.value}));setPreview(null);}}><option value="">选择已授权合约</option>{contracts.filter(c=>status.policy?.conIds.includes(c.conId)).map(c=><option key={c.conId} value={c.conId}>{c.symbol} · {c.name}</option>)}</select></label><label>方向<select value={order.side} onChange={e=>{setOrder(current=>({...current,side:e.target.value as 'BUY'|'SELL'}));setPreview(null);}}><option value="BUY">买入</option><option value="SELL">卖出已有持仓</option></select></label><label>数量（整股）<input inputMode="numeric" value={order.quantity} onChange={e=>{setOrder(current=>({...current,quantity:e.target.value}));setPreview(null);}}/></label><label>限价（USD）<input inputMode="decimal" value={order.limitPrice} onChange={e=>{setOrder(current=>({...current,limitPrice:e.target.value}));setPreview(null);}}/></label><button className="primary" disabled={!selected||!/^\d+$/.test(order.quantity)||!/^\d+(\.\d+)?$/.test(order.limitPrice)||!!busy} onClick={()=>void makePreview()}>{busy==='preview'?'正在读取行情与风控':'预览并校验订单'}</button></div></section>
    {preview&&<section className="awb-panel awb-paper-preview"><div><small>订单预览 · {new Date(preview.expiresAt).toLocaleTimeString('zh-CN',{hour12:false})} 前有效</small><h2>{preview.side==='BUY'?'买入':'卖出'} {preview.quantity} 股 {preview.symbol}</h2><dl><dt>限价</dt><dd>{preview.limitPrice} {preview.currency}</dd><dt>预留名义金额</dt><dd>{preview.reservedNotional} {preview.currency}</dd><dt>预留现金</dt><dd>{preview.reservedCash} {preview.currency}</dd><dt>账户快照</dt><dd>{preview.snapshotId}</dd></dl>{preview.warnings.map(w=><p key={w}>{w}</p>)}</div><button className="primary" disabled={!!busy} onClick={()=>void confirm()}><Check size={16}/>{busy==='confirm'?'发送中':'确认发送到 IBKR 模拟盘'}</button></section>}
    <section className="awb-panel"><div className="awb-section-heading"><h2>2. 模拟盘订单</h2><div><button disabled={!!busy} onClick={()=>execute('reconcile',async()=>{await paperRequest('reconcile',{});await load();})}><RefreshCw size={14}/>对账</button><button className="awb-outline" disabled={!!busy} onClick={()=>execute('stop',async()=>{await paperRequest('stop',{});await load();})}><CircleStop size={14}/>停止新增订单</button></div></div><div className="awb-table-scroll"><table><thead><tr><th>合约</th><th>方向 / 数量</th><th>限价</th><th>提交</th><th>执行</th><th>成交</th><th>操作</th></tr></thead><tbody>{status.orders.map(row=><tr key={row.intent.clientIntentId}><td>conId {row.intent.conId}</td><td>{row.intent.side} · {row.intent.quantity}</td><td>{row.intent.limitPrice}</td><td>{row.submission}</td><td>{row.execution}{row.reconciliationRequired&&<small>需要对账</small>}</td><td>{row.filledQuantity||'0'}<small>{row.averageFillPrice||'—'}</small></td><td><button disabled={!!busy||['FILLED','CANCELLED','REJECTED'].includes(row.execution)} onClick={()=>setCancelOrder(row)}>撤单</button></td></tr>)}</tbody></table>{!status.orders.length&&<div className="awb-empty"><p>当前没有由 SparkFlow 提交的模拟盘订单</p><small>外部订单会参与风险计算，但不会被这里擅自撤销。</small></div>}</div></section></>}
    {cancelOrder&&<div className="awb-overlay" onClick={()=>setCancelOrder(null)}><section className="awb-paper-confirm" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><AlertTriangle/><h2>确认撤销模拟盘订单？</h2><p>conId {cancelOrder.intent.conId} · {cancelOrder.intent.side} {cancelOrder.intent.quantity} 股 · 限价 {cancelOrder.intent.limitPrice}</p><div><button onClick={()=>setCancelOrder(null)}>返回</button><button className="primary" disabled={!!busy} onClick={()=>void cancel()}>{busy==='cancel'?'正在撤单':'确认撤单'}</button></div></section></div>}
  </div>;
}
