import { useEffect, useState } from 'react';
import { ArrowUpRight, Download, ShieldCheck, Sparkles } from 'lucide-react';
import type { AdjustmentPlan, Alert, AnalysisReport, PlanImpact, PortfolioPerformance, WorkbenchState } from '../../lib/ibkr/workbenchTypes';
import { exportSparkFlowResearchPdf } from '../../lib/exportResearchPdf';
import { holdingChanges, reportMarkdown } from '../../lib/ibkr/workbenchReport';
export const api='/api/ibkr-workbench/';
export async function request<T>(endpoint:string,value?:unknown,signal?:AbortSignal):Promise<T>{const r=await fetch(api+endpoint,{...(value===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}),signal});const data=await r.json();if(!r.ok)throw new Error(data.error||'账户服务暂不可用');return data;}
export const money=(v:unknown)=>v==null||v===''||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
export const pct=(v:number|null|undefined)=>v==null?'—':`${(v*100).toFixed(1)}%`;
export const time=(v:string|null|undefined)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'尚未取得';
export function EvidenceLinks({report,ids}:{report?:AnalysisReport;ids?:string[]}){return <div className="awb-citations">{ids?.map(id=>{const e=report?.evidence.find(e=>e.id===id);return e?<a key={id} href={e.url} target="_blank" rel="noreferrer" title={`${e.title} · 发布 ${time(e.publishedAt)} · 获取 ${time(e.fetchedAt)}`}>{e.source} <ArrowUpRight size={12}/></a>:null;})}</div>;}
export function ResearchDetails({id}:{id:string}){
 const [data,setData]=useState<{progress:any;evidence:any[];sections:Record<string,any>}|null>(null),[error,setError]=useState('');
 return <details className="awb-research-details" onToggle={e=>{if(e.currentTarget.open)void request<any>(`research/${id}`).then(setData).catch(()=>setError('该旧任务没有阶段记录，请新建研究。'));}}><summary>查看已保存的资料与章节</summary>{error&&<p>{error}</p>}{data&&<div className="awb-panel"><small>冻结资料时间 {time(data.progress.startedAt)} · 恢复任务沿用该快照与已收集证据</small>{Object.entries(data.sections).filter(([key])=>key.startsWith('holdings:')).flatMap(([,v])=>v.holdings).map((h:any)=><article className="awb-view" key={h.symbol}><h3>{h.symbol}</h3><p>{h.fact}</p><p>短期 · {h.shortTerm}</p><p>长期 · {h.longTerm}</p></article>)}<div className="awb-citations">{data.evidence.map(e=><a href={e.url} target="_blank" rel="noreferrer" key={e.id}>{e.symbols.join(' · ')} {e.title}</a>)}</div><details><summary>检索与调用记录</summary>{data.progress.trace.map((t:any,i:number)=><p key={i} className="awb-trace">{t.ok?'✓':'×'} {t.tool} · {t.target}</p>)}</details></div>}</details>;
}
export function PerformancePanel({state}:{state:WorkbenchState}){
 const [performance,setPerformance]=useState<PortfolioPerformance|undefined>(state.performance),[range,setRange]=useState(30),[mode,setMode]=useState<'nav'|'return'>('nav'),[hover,setHover]=useState<number|null>(null);
 useEffect(()=>{setPerformance(state.performance);const c=new AbortController();void request<PortfolioPerformance>('performance',undefined,c.signal).then(setPerformance).catch(()=>{});return()=>c.abort();},[state.snapshot.accountKey,state.preferences.benchmark]);
 const all=performance?.points??[];const end=all[all.length-1]?.date;const ranged=all.filter(p=>!end||Date.parse(p.date)>=Date.parse(end)-range*86400000);const compare=mode==='return'&&ranged.some(p=>p.benchmarkReturn!=null);const points=compare?ranged.filter(p=>p.cumulativeReturn!==null&&p.benchmarkReturn!=null):ranged;
 const twr=performance?.returnMethod==='TWR';const base=points.find(p=>p.cumulativeReturn!==null)?.cumulativeReturn;const baseB=points.find(p=>p.benchmarkReturn!=null)?.benchmarkReturn;
 const values=points.map(p=>mode==='nav'?p.nav:!twr?p.cumulativeReturn:base!=null&&p.cumulativeReturn!=null?(1+p.cumulativeReturn)/(1+base)-1:null);
 const benchmarks=points.map(p=>mode==='return'&&baseB!=null&&p.benchmarkReturn!=null?(1+p.benchmarkReturn)/(1+baseB)-1:null);
 const valid=[...values,...benchmarks].filter((v):v is number=>v!==null);const min=Math.min(...valid),max=Math.max(...valid),spread=Math.max((max-min)*1.2,Math.abs(max)*.005,.001),bottom=min-spread*.1;
 const aligned=points.map((p,i)=>({a:values[i],b:benchmarks[i]})).filter(p=>p.a!==null&&p.b!==null);const lastAligned=aligned[aligned.length-1];const excess=mode==='return'&&twr&&lastAligned?lastAligned.a!-lastAligned.b!:null;
 const line=(vs:(number|null)[])=>vs.map((v,i)=>v===null?'':`${i===0||vs[i-1]===null?'M':'L'}${48+i/Math.max(1,vs.length-1)*610},${215-(v-bottom)/spread*180}`).join(' ');
 return <section className="awb-panel awb-performance"><div className="awb-section-heading"><h2>资产表现</h2><div className="awb-segment">{[[7,'1周'],[30,'1月'],[90,'3月'],[365,'1年']].map(([n,label])=><button key={n} aria-pressed={range===n} onClick={()=>{setRange(Number(n));setHover(null);}}>{label}</button>)}</div></div><div className="awb-section-heading"><div className="awb-segment"><button aria-pressed={mode==='nav'} onClick={()=>setMode('nav')}>资产净值</button><button disabled={!performance?.returnMethod} aria-pressed={mode==='return'} onClick={()=>setMode('return')}>投资收益</button></div><small>{performance?.currency??state.snapshot.baseCurrency} · {hover!==null&&points[hover]?`${points[hover].date}  ${mode==='nav'?money(values[hover]):pct(values[hover])}`:performance?.source}</small></div>
 {valid.length>1?<svg viewBox="0 0 690 255" role="img" aria-label="账户资产表现曲线" onMouseLeave={()=>setHover(null)} onMouseMove={e=>{const rect=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(points.length-1,Math.round(((e.clientX-rect.left)/rect.width*690-48)/610*(points.length-1)))));}}><defs><linearGradient id="awb-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#70dcba" stopOpacity=".2"/><stop offset="1" stopColor="#70dcba" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=><g key={i}><path d={`M48 ${35+i*60} H658`} stroke="#20352d" strokeDasharray="3 5"/><text x="0" y={39+i*60}>{mode==='nav'?money(bottom+(215-35-i*60)/180*spread):pct(bottom+(215-35-i*60)/180*spread)}</text></g>)}<path d={`${line(values)} L658 225 L48 225 Z`} fill="url(#awb-chart-fill)"/><path d={line(values)} fill="none" stroke="#70dcba" strokeWidth="2.5"/><path d={line(benchmarks)} fill="none" stroke="#afabc8" strokeWidth="1.5" strokeDasharray="5 4"/>{hover!==null&&<path d={`M${48+hover/Math.max(1,points.length-1)*610} 25V225`} stroke="#94b1a6"/>}<text x="48" y="250">{points[0]?.date}</text><text x="658" y="250" textAnchor="end">{points[points.length-1]?.date}</text></svg>:<div className="awb-chart-empty"><span className="awb-chart-placeholder"/><strong>开始积累真实账户轨迹</strong><p>{points.length?`已记录 ${points.length} 个日期，至少两个点后显示曲线`:'官方历史尚未取得，同步后保存本地净值'}</p></div>}
 <div className="awb-allocation">{state.metrics?.sectors.slice(0,3).map((s,i)=><span key={s.name}><i style={{background:['#70dcba','#a7b2d7','#d9b879'][i]}}/>{s.name} {pct(s.weight)}</span>)}<span><i style={{background:'#8eaaa0'}}/>现金 {pct(state.metrics?.cashWeight)}</span></div>{mode==='return'&&<div className="awb-performance-stats"><span>区间超额 <b>{pct(excess)}</b></span><span>波动率比较 <b>{performance?.volatilityRatio==null?'至少需要 60 个共同交易日':`${performance.volatilityRatio.toFixed(2)}×（完整共同历史）`}</b></span><small>{performance?.benchmarkSource??'基准未取得'}</small></div>}<small className="awb-muted">{performance?.note??'净值变化含出入金，不能直接视为投资收益。'}{mode==='return'&&` · 基准 ${performance?.benchmark}（复权）`}</small></section>;
}
export function AnalysisPage({state,report,onSelect,onPlan}:{state:WorkbenchState;report?:AnalysisReport;onSelect:(r:AnalysisReport)=>void;onPlan:()=>void}){
 const [error,setError]=useState(''),[exporting,setExporting]=useState(false);const previous=report?state.reports[state.reports.findIndex(r=>r.id===report.id)+1]:undefined;
 if(!report)return <section className="awb-panel awb-empty"><Sparkles size={32}/><h2>建立第一份投资组合研究</h2><p>研究会搜索持仓事件、阅读原文，再形成短期与长期判断。</p></section>;
 return <><div className="awb-report-toolbar"><select aria-label="历史报告" value={report.id} onChange={e=>{const r=state.reports.find(r=>r.id===e.target.value);if(r)onSelect(r);}}>{state.reports.map(r=><option key={r.id} value={r.id}>{time(r.generatedAt)} · {r.version===2?'主动研究':'旧版分析'}</option>)}</select><span>{report.model} · {report.research?.sources??report.evidence.length} 个来源</span><a href={`${api}reports/${report.id}/html`}><Download size={14}/>HTML</a><button disabled={exporting} onClick={async()=>{setExporting(true);try{await exportSparkFlowResearchPdf(reportMarkdown(report));}catch{setError('PDF 导出失败，请使用 HTML');}finally{setExporting(false);}}}><Download size={14}/>{exporting?'导出中':'PDF'}</button></div>{error&&<p role="alert">{error}</p>}
 <div className="awb-analysis-grid"><div className="awb-stack"><section className="awb-panel awb-thesis"><span className="awb-eyebrow">AI SUMMARY · {report.version===2?'有据可查':'旧版分析'}</span><h2>{report.content.headline??'组合判断与研究结论'}</h2>{(report.content.briefPoints??[report.content.brief]).map((p,i)=><p key={i}>{p}</p>)}<EvidenceLinks report={report} ids={report.content.evidenceIds}/><hr/><h3>市场背景</h3><p>{report.content.marketContext}</p><hr/><h3>持仓诊断</h3><p>{report.content.portfolioRisk}</p><div className="awb-sector-bars">{report.metrics?.sectors.map(s=><div key={s.name}><span>{s.name}</span><b>{pct(s.weight)}</b><i style={{width:`${Math.min(100,s.weight*100)}%`}}/></div>)}</div></section>
 {report.content.holdings.map(h=><section className="awb-panel awb-holding-research" key={h.symbol}><div className="awb-section-heading"><h2>{h.symbol}</h2><small>短期 + 长期</small></div><p>{h.background}</p>{h.fact&&<p><b>已核实事实</b> {h.fact}</p>}{h.impact&&<p><b>影响机制</b> {h.impact}</p>}<div className="awb-view"><b>短期应对</b><p>{h.shortTerm}</p></div><div className="awb-view"><b>长期逻辑</b><p>{h.longTerm}</p></div>{h.counterEvidence&&<p className="awb-muted">反对证据 · {h.counterEvidence}</p>}{h.invalidation&&<p className="awb-muted">失效条件 · {h.invalidation}</p>}{h.support?.map((s,i)=><blockquote className="awb-original-quote" key={i}>{s.quote}</blockquote>)}<EvidenceLinks report={report} ids={h.evidenceIds}/></section>)}</div>
 <aside className="awb-stack">{previous&&<details className="awb-panel"><summary>与上一份报告对比</summary><p>净资产 {money(previous.snapshot.metrics.netLiquidation)} → {money(report.snapshot.metrics.netLiquidation)}</p><small>净资产变化包含出入金，不等于投资收益。</small>{holdingChanges(previous,report).map(c=><p key={c.conId}>{c.symbol} 数量 {c.before} → {c.after}</p>)}<p>上一份结论 · {previous.content.headline??previous.content.brief.slice(0,120)}</p></details>}<section className="awb-panel"><h2>建议行动</h2>{report.content.actions.map((a,i)=><article className="awb-action-card" key={i}><span className="awb-action-number">{String(i+1).padStart(2,'0')}</span><div><h3>{a.symbol} · {{hold:'维持',watch:'观察',increase:'增持',reduce:'减持'}[a.action]}</h3><span className="awb-tag">{a.horizon==='short'?'短期':'长期'} · 目标 {pct(a.targetWeight)}</span><p>{a.rationale}</p><dl><dt>触发条件</dt><dd>{a.trigger}</dd><dt>反对证据</dt><dd>{a.counterEvidence}</dd><dt>失效条件</dt><dd>{a.invalidation}</dd></dl><EvidenceLinks report={report} ids={a.evidenceIds}/></div></article>)}<button className="primary awb-full" onClick={onPlan}>制定整份调整计划 <ArrowUpRight size={15}/></button></section><section className="awb-panel"><h2>情景分析</h2><p>在调整计划中统一模拟目标仓位、现金与价格涨跌情景。</p><p className="awb-muted">不赋予假设情景概率或预测收益；所有建议合并计算后检查资金约束。</p></section><section className="awb-panel"><h2>证据与数据缺口</h2>{report.content.gaps.map((g,i)=><p className="awb-gap" key={i}>{g}</p>)}<details><summary>查看研究记录</summary>{report.research?.trace.map((t,i)=><p className="awb-trace" key={i}>{t.ok?'✓':'×'} {t.tool} · {t.target}<small>{time(t.at)}</small></p>)}</details>{report.evidence.map(e=><a className="awb-detail-evidence" key={e.id} href={e.url} target="_blank" rel="noreferrer">{e.title}<small>{e.source} · 发布 {e.publishedAt?time(e.publishedAt):'未核实'}<br/>获取 {time(e.fetchedAt)} · {e.read?'已阅读':'摘要线索'}</small></a>)}</section></aside></div></>;
}
export function PlanPanel({state,alert,existing,reportId,onSaved}:{state:WorkbenchState;alert?:Alert;existing?:AdjustmentPlan;reportId?:string;onSaved:()=>Promise<void>}){
 const eligible=state.snapshot.positions.filter(p=>p.assetType==='STK'&&p.currency==='USD'&&Number(p.quantity)>=0);const [title,setTitle]=useState(existing?.title??(alert?`${alert.title} · 调整计划`:'组合调整计划'));
 const [linkedReport,setLinkedReport]=useState<string|undefined>(existing?.reportId??alert?.reportId??reportId??state.reports[0]?.id);
 const [steps,setSteps]=useState<AdjustmentPlan['steps']>(existing?.steps??[]),[shock,setShock]=useState(-10),[impact,setImpact]=useState<PlanImpact|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState<AdjustmentPlan['status']>(existing?.status??'watching');
 const plan={id:existing?.id,title,reportId:linkedReport,alertId:existing?.alertId??alert?.id,status,steps};
 const change=(next:AdjustmentPlan['steps'])=>{setSteps(next);setImpact(null);};
 const execute=async(save:boolean)=>{setBusy(true);setError('');try{if(save){await request('plans',plan);await onSaved();}else setImpact(await request<PlanImpact>('simulate',{plan,shock:shock/100}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="awb-panel awb-plan"><div className="awb-section-heading"><h2>调整计划</h2><ShieldCheck size={18}/></div><label>计划名称<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120}/></label><label>关联报告<select value={linkedReport??''} onChange={e=>setLinkedReport(e.target.value||undefined)}><option value="">不关联报告</option>{state.reports.map(r=><option value={r.id} key={r.id}>{time(r.generatedAt)}</option>)}</select></label><label>处理状态<select value={status} onChange={e=>setStatus(e.target.value as AdjustmentPlan['status'])}><option value="watching">观察中</option><option value="triggered">条件满足（本人确认）</option><option value="handled">已处理</option><option value="invalidated">已失效</option></select></label><select aria-label="添加计划持仓" value="" onChange={e=>{const h=eligible.find(h=>h.conId===Number(e.target.value));if(h)change([...steps,{conId:h.conId,targetWeight:Math.max(0,Number(h.marketValue)/Number(state.snapshot.metrics.netLiquidation)),trigger:alert?.trigger??'等待本人核实事件与行情后确认',exit:'基本判断失效时重新评估',batches:'分批执行前重新核对现金与价格'}]);}}><option value="">＋ 添加调整持仓</option>{eligible.filter(h=>!steps.some(s=>s.conId===h.conId)).map(h=><option value={h.conId} key={h.conId}>{h.symbol}</option>)}</select>
 {steps.map((s,i)=>{const update=(v:Partial<typeof s>)=>change(steps.map((a,j)=>i===j?{...a,...v}:a));return <div className="awb-plan-step" key={s.conId}><div className="awb-section-heading"><h3>{eligible.find(h=>h.conId===s.conId)?.symbol}</h3><button onClick={()=>change(steps.filter((_,j)=>j!==i))}>移除</button></div><label>目标仓位 %<input type="number" min="0" max="100" step="0.01" value={Number((s.targetWeight*100).toFixed(4))} onChange={e=>update({targetWeight:Number(e.target.value)/100})}/></label><label>价格触发<select value={s.priceCondition?.direction??'none'} onChange={e=>update({priceCondition:e.target.value==='none'?undefined:{direction:e.target.value as 'above'|'below',price:s.priceCondition?.price??state.quotes.find(q=>q.conId===s.conId)?.price??1}})}><option value="none">不设置价格条件</option><option value="above">报价达到或高于</option><option value="below">报价达到或低于</option></select></label>{s.priceCondition&&<><label>触发价格<input type="number" min="0.00000001" step="any" value={s.priceCondition.price} onChange={e=>update({priceCondition:{...s.priceCondition!,price:Number(e.target.value)}})}/></label><label className="awb-checkbox"><input type="checkbox" checked={s.trigger==='仅价格条件'} onChange={e=>update({trigger:e.target.checked?'仅价格条件':'本人确认价格与事件条件均已满足'})}/>仅价格条件，允许自动判定</label><small>自动判定要求全部步骤仅有价格条件，且报价在三分钟内；含财报、政策等条件时由你确认。</small></>}<label>触发条件<textarea value={s.trigger} onChange={e=>update({trigger:e.target.value})}/></label><label>分批安排<textarea value={s.batches} onChange={e=>update({batches:e.target.value})}/></label><label>退出 / 失效条件<textarea value={s.exit} onChange={e=>update({exit:e.target.value})}/></label></div>;})}
 <label>持仓统一涨跌情景 %<input type="number" min="-100" max="100" value={shock} onChange={e=>{setShock(Number(e.target.value));setImpact(null);}}/></label>{error&&<p className="awb-message error" role="alert">{error}</p>}{impact&&<div className="awb-impact"><h3>整份计划的影响</h3>{state.preferences.maxDrawdown!=null&&-impact.scenarioPnl/Number(state.snapshot.metrics.netLiquidation)>state.preferences.maxDrawdown&&<p className="attention">该假设情景的亏损超过你设置的可接受回撤。</p>}<dl><dt>现金</dt><dd>{money(impact.cashBefore)} → {money(impact.cashAfter)}</dd><dt>总仓位</dt><dd>{pct(impact.investedBefore)} → {pct(impact.investedAfter)}</dd><dt>最大单一仓位</dt><dd>{pct(impact.concentrationBefore)} → {pct(impact.concentrationAfter)}</dd><dt>情景盈亏</dt><dd>{money(impact.scenarioPnl)} {state.snapshot.baseCurrency}</dd></dl>{impact.sectors.map(s=><p key={s.name}>{s.name} {pct(s.before)} → {pct(s.after)}</p>)}{impact.rows.filter(r=>Math.abs(r.deltaValue)>.000001).map(r=><p key={r.conId}>{r.symbol} 调整金额 {r.deltaValue>0?'+':''}{money(r.deltaValue)}</p>)}<small>估值时间 {time(impact.asOf)}</small>{impact.assumptions.map(a=><small key={a}>{a}</small>)}</div>}<div className="awb-plan-buttons"><button disabled={busy||!steps.length} onClick={()=>void execute(false)}>模拟影响</button><button className="primary" disabled={busy||!steps.length} onClick={()=>void execute(true)}>保存计划</button></div><small>事件条件由你确认。计划不发送订单；未核实交易精度时只估算金额和权重。</small></section>;
}
