import type { Snapshot, Position } from './types';

export type Holding = Position & { assetType?: string; exchange?: string; name?: string; unrealizedPnl?: string | null; dailyPnl?: string | null; sector?: string; industry?: string; instrumentType?: string; profileUrl?: string };
export type AccountSnapshot = Omit<Snapshot, 'positions'> & { positions: Holding[] };
export type MarketQuote = { conId: number; symbol: string; secid?: string; name?: string; price: number | null; changePercent: number | null; asOf: string | null; fetchedAt: string; source: string; status: 'delayed' | 'stale' | 'missing' | 'unmapped' | 'unsupported'; currency: string; sourceUrl: string };
export type Evidence = { id: string; title: string; summary: string; url: string; source: string; publishedAt: string | null; fetchedAt: string; symbols: string[]; kind: 'news' | 'macro' | 'filing' | 'profile' | 'market'; content?: string; primary?: boolean; read?: boolean; query?: string; cached?: boolean };
export type Preferences = { horizon: 'both' | 'long' | 'swing'; targetWeight: number | null; cashFloor: number | null; maxDrawdown: number | null; daily: boolean; eventAnalysis: boolean; maxAutomatic: number; cooldownMinutes: number; maxAiCalls: number; benchmark?: 'SPY' | 'QQQ' | 'none' };
export type Alert = { id: string; key: string; kind: 'risk' | 'opportunity' | 'change'; title: string; detail: string; symbols: string[]; createdAt: string; read: boolean; resolved: boolean; active?: boolean; reportId?: string; evidenceIds: string[]; trigger?: string; invalidation?: string; priority?: 'high' | 'medium' | 'low'; watched?: boolean };
export type ActionIdea = { symbol: string; action: 'hold' | 'watch' | 'increase' | 'reduce'; horizon: 'short' | 'long'; priority?: 'high' | 'medium' | 'low'; rationale: string; executionWindow?: string; riskControl?: string; expectedImpact?: string; counterEvidence: string; trigger: string; invalidation: string; targetWeight: number | null; evidenceIds: string[]; shares?: number; estimatedCashAfter?: number; estimatedWeightAfter?: number };
export type AnalysisScenario = { name: 'base' | 'upside' | 'downside'; assumptions: string; accountImpact: string; response: string };
export type AnalysisMonitor = { indicator: string; warningLine: string; action: string };
export type AnalysisContent = { headline?: string; briefPoints?: string[]; evidenceIds?: string[]; brief: string; accountSummary: string; portfolioRisk: string; benchmarkComparison?: string; marketContext: string; holdings: { symbol: string; background: string; shortTerm: string; longTerm: string; support?: {evidenceId:string;quote:string}[]; fact?: string; impact?: string; counterEvidence?: string; invalidation?: string; evidenceIds?: string[] }[]; opportunities: string[]; risks: string[]; scenarios?: AnalysisScenario[]; actions: ActionIdea[]; targetAllocation?: string; monitoring?: AnalysisMonitor[]; limitations?: string[]; disclaimer?: string; gaps: string[] };
export type AnalysisReport = { id: string; accountKey: string; snapshotId: string; snapshotHash: string; generatedAt: string; provider: string; model: string; kind: 'daily' | 'event' | 'manual' | 'chat'; question?: string; dateKey?: string; evidence: Evidence[]; quotes: MarketQuote[]; snapshot: AccountSnapshot; content: AnalysisContent; version?: 2; research?: ResearchProgress; metrics?: PortfolioMetrics };
export type AnalysisJob = { id: string; kind: AnalysisReport['kind']; state: 'running' | 'completed' | 'failed' | 'interrupted' | 'partial' | 'cancelled'; startedAt: string; reportId?: string; error?: string; progress?: ResearchProgress; failureCategory?: string };
export type AiModel = { provider: string; model: string; fingerprint: string; configured: boolean };
export type WorkbenchState = { source: 'mcp' | 'gateway'; connection: { state: string; authorized?: boolean; detail: string; tools: { name: string; description: string; inputSchema: unknown }[]; accounts: { key: string; label: string }[] }; snapshot: AccountSnapshot; quotes: MarketQuote[]; evidence: Evidence[]; alerts: Alert[]; reports: AnalysisReport[]; jobs: AnalysisJob[]; preferences: Preferences; ai: AiModel & { enabled: boolean; fields: string[]; usedToday: number }; nextSyncAt: string | null; calendarSupported: boolean; dailyBrief?: DailyBriefStatus; performance?: PortfolioPerformance; plans?: AdjustmentPlan[]; metrics?: PortfolioMetrics; researchServices?: string[] };

export type ResearchProgress = { strategy?: 'portfolio'; stage: string; covered: string[]; total: number; sources: number; searches: number; reads: number; modelCalls: number; maxCalls: number; startedAt: string; updatedAt: string; complete: boolean; gaps: string[]; trace: { at: string; tool: string; target: string; ok: boolean }[] };
export type PortfolioMetrics = { investedWeight: number | null; cashWeight: number | null; topWeight: number | null; riskLevel: string; reasons: string[]; sectors: { name: string; weight: number }[]; sectorCoverage: number };
export type DailyBriefContent = { headline: string; summary: string; risk: string; watch: string[]; gaps: string[] };
export type DailyBrief = { id: string; accountKey: string; snapshotId: string; snapshotHash: string; snapshotAsOf: string | null; sessionDate: string | null; generatedAt: string; provider: string; model: string; promptVersion: string; content: DailyBriefContent; facts: Record<string, { label: string; display: string; source: string; asOf: string | null }> };
export type DailyBriefStatus = { latest?: DailyBrief; enabled: boolean; state: 'ready' | 'waiting' | 'running' | 'failed' | 'blocked' | 'disabled'; detail: string; nextRunAt: string | null; dueSession: string | null; calendarSupported: boolean };
export type PerformancePoint = { date: string; nav: number | null; cumulativeReturn: number | null; benchmarkReturn?: number | null };
export type PortfolioPerformance = { points: PerformancePoint[]; source: string; fetchedAt: string | null; currency: string | null; returnMethod: string | null; benchmark: string; benchmarkSource?: string; benchmarkFetchedAt?: string; note: string; excessReturn?: number | null; volatilityRatio?: number | null };
export type AdjustmentPlan = { id: string; title: string; reportId?: string; alertId?: string; status: 'watching' | 'triggered' | 'handled' | 'invalidated'; createdAt: string; updatedAt: string; snapshotId: string; steps: { conId: number; targetWeight: number; trigger: string; exit: string; batches: string; priceCondition?: { direction: 'above' | 'below'; price: number } }[] };
export type PlanImpact = { cashBefore: number; cashAfter: number; investedBefore: number; investedAfter: number; concentrationBefore: number; concentrationAfter: number; scenarioPnl: number; rows: { conId: number; symbol: string; before: number; after: number; deltaValue: number }[]; sectors: { name: string; before: number; after: number }[]; asOf: string | null; assumptions: string[] };
